# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Arc Camera' do
  pod 'PBJVision'
end

target 'Arc CameraTests' do

end

target 'Arc CameraUITests' do

end

